create table
  public.global_inventory (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    num_red_ml integer not null default 0,
    gold integer not null default 100,
    num_green_ml integer not null default 0,
    num_blue_ml integer not null default 0,
    num_dark_ml integer not null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potions (
    id bigint generated by default as identity,
    sku text not null,
    name text not null,
    price integer not null default 50,
    red integer not null default 0,
    green integer not null default 0,
    blue integer not null default 0,
    dark integer not null default 0,
    constraint potions_pkey primary key (id),
    constraint potions_name_key unique (name),
    constraint potions_sku_key unique (sku)
  ) tablespace pg_default;

create table
  public.potion_quantities (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    potion_id bigint not null,
    delta integer not null default 0,
    constraint potion_quantities_pkey primary key (id),
    constraint potion_quantities_potion_id_fkey foreign key (potion_id) references potions (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.shopping_carts (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default (now() at time zone 'utc'::text),
    customer text not null,
    constraint shopping_carts_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_contents (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    cart_id bigint not null,
    potion_id bigint not null,
    quantity_requested integer not null,
    constraint cart_contents_pkey primary key (id),
    constraint cart_contents_cart_id_fkey foreign key (cart_id) references shopping_carts (id) on update cascade on delete cascade,
    constraint cart_contents_potion_id_fkey foreign key (potion_id) references potions (id) on delete cascade
  ) tablespace pg_default;

create table
  public.transactions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    cart_id bigint not null,
    success boolean not null,
    payment text not null,
    gold_paid integer not null,
    constraint transactions_pkey primary key (id),
    constraint transactions_cart_id_fkey foreign key (cart_id) references shopping_carts (id) on update cascade on delete cascade
  ) tablespace pg_default;

  create table
  public.exclusions (
    id bigint generated by default as identity,
    day smallint not null,
    sku text not null,
    constraint exclusions_pkey primary key (id),
    constraint exclusions_sku_fkey foreign key (sku) references potions (sku) on update cascade on delete cascade
  ) tablespace pg_default;

  create table
  public.shop_state (
    id bigint generated by default as identity,
    phase smallint not null default '1'::smallint,
    recents_threshold integer not null default 9,
    recents_interval integer not null default 2,
    sell_off_price integer not null default 10,
    bottle_max integer not null default 50,
    constraint shop_state_pkey primary key (id)
  ) tablespace pg_default;

  INSERT INTO global_inventory DEFAULT VALUES; 

  INSERT INTO shop_state DEFAULT VALUES; 

  INSERT INTO potions (sku, price, name, red, green, blue, dark)
    VALUES ('red_potion', 50, 'Red', 100, 0, 0, 0),
      ('green_potion', 50, 'Green', 0, 100, 0, 0),
      ('blue_potion', 50, 'Blue', 0, 0, 100, 0),
      ('dark_potion', 50, 'Dark', 0, 0, 0, 100),
      ('purple_potion', 50, 'Purple', 50, 0, 50, 0),
      ('rusty_potion', 50, 'Rusty', 50, 50, 0, 0),
      ('vogue_blue_potion', 50, 'Vogue Blue', 0, 0, 67, 33),
      ('light_blue_potion', 50, 'Light Blue', 28, 35, 37, 0),
      ('mahogany_potion', 50, 'Mahogany', 67, 0, 0, 33),
      ('deep_fir_potion', 50, 'Deep Fir', 0, 25, 0, 75),
      ('forest_green_potion', 50, 'Forest Green', 9, 37, 9, 45),
      ('rainbow_potion', 50, 'Rainbow', 25, 25, 25, 25),
      ('white_potion', 50, 'White', 34, 33, 33, 0),
      ('orange_potion', 50, 'Orange', 67, 33, 0, 0),
      ('pink_potion', 50, 'Pink', 45, 33, 22, 0),
      ('grey_potion', 50, 'Grey', 17, 17, 17, 49)