create table
  public.global_inventory (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    num_potions integer null,
    num_red_ml integer null,
    gold integer null,
    num_green_ml integer null,
    num_blue_ml integer null,
    num_dark_ml integer null,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potions (
    id bigint generated by default as identity,
    sku text null,
    name text null,
    price integer null default 50,
    red integer null default 0,
    green integer null default 0,
    blue integer null default 0,
    dark integer null default 0,
    quantity integer null default 0,
    constraint potions_pkey primary key (id),
    constraint potions_sku_key unique (sku)
  ) tablespace pg_default;

create table
  public.shopping_carts (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    customer text null,
    constraint shopping_carts_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_contents (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    cart_id bigint null,
    potion_sku text null,
    quantity_requested integer null,
    constraint cart_contents_pkey primary key (id),
    constraint cart_contents_cart_id_fkey foreign key (cart_id) references shopping_carts (id) on update cascade on delete cascade,
    constraint cart_contents_potion_sku_fkey foreign key (potion_sku) references potions (sku) on update cascade
  ) tablespace pg_default;

create table
  public.transactions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    cart_id bigint null,
    success boolean null,
    payment text null,
    gold_paid integer null,
    constraint transactions_pkey primary key (id),
    constraint transactions_cart_id_key unique (cart_id),
    constraint transactions_cart_id_fkey foreign key (cart_id) references shopping_carts (id) on update cascade on delete cascade
  ) tablespace pg_default;